"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import Nav from "../../components/Nav";
import Footer from "../../components/Footer";

const sources = [
 {icon:"☀️",title:"Energi Surya",tag:"Cahaya → listrik",front:"Sel surya menangkap energi cahaya matahari.",back:"Cara kerja: foton mengenai sel fotovoltaik dan menggerakkan elektron sehingga timbul arus listrik.\n\nContoh: PLTS atap dan lampu jalan surya.\n\nKelebihan: modular, senyap, tanpa emisi saat beroperasi.\n\nTantangan: bergantung cuaca dan memerlukan penyimpanan atau jaringan pendukung."},
 {icon:"💨",title:"Energi Angin",tag:"Gerak → listrik",front:"Angin memutar bilah turbin dan generator.",back:"Cara kerja: energi kinetik angin memutar rotor, lalu generator mengubah putaran menjadi listrik.\n\nContoh: PLTB Sidrap dan Jeneponto.\n\nKelebihan: penggunaan air sangat kecil.\n\nTantangan: optimal hanya di wilayah dengan kecepatan angin memadai dan stabil."},
 {icon:"💧",title:"Energi Air",tag:"Gerak → listrik",front:"Aliran atau jatuhan air memutar turbin.",back:"Cara kerja: energi potensial dan kinetik air memutar turbin yang tersambung ke generator.\n\nContoh: PLTA dan mikrohidro.\n\nKelebihan: relatif stabil dan dapat merespons kebutuhan listrik.\n\nTantangan: bendungan dapat mengubah ekosistem dan kehidupan masyarakat sekitar."},
 {icon:"🌿",title:"Biomassa",tag:"Kimia → panas/gas",front:"Bahan organik diolah menjadi panas, bahan bakar, atau gas.",back:"Cara kerja: sisa tanaman, kayu, atau kotoran ternak dibakar atau difermentasi.\n\nContoh: biogas dan briket limbah pertanian.\n\nKelebihan: dapat memanfaatkan residu organik.\n\nTantangan: tidak otomatis bersih; bahan baku dan emisinya harus dikelola secara berkelanjutan."},
 {icon:"🌋",title:"Panas Bumi",tag:"Panas → listrik",front:"Panas dari dalam bumi menghasilkan uap untuk memutar turbin.",back:"Cara kerja: panas bawah permukaan memanaskan fluida; uap atau fluida panas menggerakkan turbin.\n\nContoh: PLTP Sarulla di Sumatra Utara.\n\nKelebihan: dapat beroperasi siang dan malam.\n\nTantangan: lokasi terbatas, eksplorasi mahal, dan perlu pengelolaan lingkungan."}
];
const compare = {surya:["Melimpah di siang hari","Berubah mengikuti cuaca","Atap rumah hingga pembangkit"],angin:["Tanpa bahan bakar","Memerlukan angin stabil","Pesisir dan dataran terbuka"],air:["Relatif stabil","Dipengaruhi debit air","Sungai dan bendungan"],biomassa:["Memanfaatkan bahan organik","Dapat menghasilkan emisi","Dekat sumber limbah"],geotermal:["Tersedia 24 jam","Hanya lokasi tertentu","Wilayah panas bumi"]};

export default function Belajar(){
 const [flipped,setFlipped]=useState<number[]>([]); const [tab,setTab]=useState<keyof typeof compare>("surya"); const [flow,setFlow]=useState(0); const [watts,setWatts]=useState(12); const [hours,setHours]=useState(6);
 const kwh=useMemo(()=>((watts*hours*30)/1000).toFixed(2),[watts,hours]);
 const steps=["Sumber energi tersedia di alam","Energi ditangkap oleh alat","Generator/sel mengubahnya menjadi listrik","Listrik disalurkan ke pengguna"];
 return <main><Nav active="belajar"/><header className="pageHero"><span className="sectionNo">PUSAT BELAJAR</span><h1>Pahami energi dari<br/>sumber hingga digunakan.</h1><p>Ikuti materi secara berurutan atau pilih bagian yang ingin kamu eksplorasi.</p><div className="chapterLinks"><a href="#dasar">01 Dasar energi</a><a href="#flashcard">02 Sumber</a><a href="#bandingkan">03 Bandingkan</a><a href="#simulasi">04 Aksi</a></div></header>
 <section className="lesson" id="dasar"><div className="lessonSide"><span className="sectionNo">01 — DASAR ENERGI</span><h2>Energi tidak hilang, tetapi berubah bentuk.</h2></div><div className="lessonBody"><p className="lead">Energi adalah kemampuan untuk melakukan kerja atau menyebabkan perubahan. Kita tidak menciptakan energi dari ketiadaan; kita <strong>mengubahnya dari satu bentuk ke bentuk lain.</strong></p><div className="transform"><span>☀️<small>Cahaya</small></span><i>→</i><span>🔋<small>Listrik</small></span><i>→</i><span>💡<small>Cahaya + panas</small></span></div><div className="note"><b>Ingat:</b> sumber energi berbeda dengan bentuk energi. Matahari adalah sumber; cahaya dan panas adalah bentuk energi yang dibawanya.</div><h3>Terbarukan vs. tidak terbarukan</h3><div className="definitionGrid"><article><b>TERBARUKAN</b><p>Dipulihkan oleh proses alam dalam skala waktu manusia. Tetap perlu dikelola karena alat, lahan, dan ekosistemnya memiliki batas.</p></article><article><b>TIDAK TERBARUKAN</b><p>Terbentuk selama jutaan tahun dan digunakan jauh lebih cepat daripada proses pembentukannya, misalnya batu bara, minyak, dan gas.</p></article></div></div></section>
 <section className="cardsSection" id="flashcard"><div className="sectionHead"><div><span className="sectionNo light">02 — FLASHCARD</span><h2>Lima sumber energi terbarukan</h2></div><p>Klik kartu untuk melihat cara kerja, contoh di Indonesia, kelebihan, dan tantangannya.</p></div><div className="cards">{sources.map((c,i)=><button key={c.title} className={`energyCard ${flipped.includes(i)?"isFlipped":""}`} onClick={()=>setFlipped(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i])}><div className="cardInner"><div className="cardFace front"><span className="cardNum">0{i+1}</span><div className="cardIcon">{c.icon}</div><small>{c.tag}</small><h3>{c.title}</h3><p>{c.front}</p><span className="flipLabel">BALIK KARTU ↗</span></div><div className="cardFace back"><span className="cardNum">0{i+1}</span><h3>{c.title}</h3><p>{c.back}</p><span className="flipLabel">KEMBALI ↙</span></div></div></button>)}</div></section>
 <section className="compareSection" id="bandingkan"><div><span className="sectionNo">03 — LAB PERBANDINGAN</span><h2>Tidak ada satu sumber yang sempurna.</h2><p>Pilih sumber energi untuk membandingkan karakter dan tempat penerapannya.</p><div className="tabs">{Object.keys(compare).map(k=><button className={tab===k?"active":""} key={k} onClick={()=>setTab(k as keyof typeof compare)}>{k}</button>)}</div></div><div className="comparePanel"><div className="bigIcon">{sources[Object.keys(compare).indexOf(tab)].icon}</div><h3>{sources[Object.keys(compare).indexOf(tab)].title}</h3><ul><li><b>Kekuatan</b>{compare[tab][0]}</li><li><b>Keterbatasan</b>{compare[tab][1]}</li><li><b>Cocok diterapkan</b>{compare[tab][2]}</li></ul><p className="caption">Pemilihan sumber mempertimbangkan potensi alam, kebutuhan listrik, biaya, jaringan, masyarakat, dan dampak lingkungan.</p></div></section>
 <section className="flowSection"><span className="sectionNo light">AKTIVITAS — TELUSURI ALIRAN</span><h2>Bagaimana energi sampai ke rumah?</h2><p>Klik tombol untuk mengikuti perubahan dari sumber alam menjadi listrik.</p><div className="flowTrack">{steps.map((s,i)=><button key={s} className={i<=flow?"shown":""} onClick={()=>setFlow(i)}><b>0{i+1}</b><span>{s}</span></button>)}</div><button className="primary plain" onClick={()=>setFlow(flow===3?0:flow+1)}>{flow===3?"Ulangi alur ↻":"Langkah berikutnya →"}</button></section>
 <section className="calculator" id="simulasi"><div><span className="sectionNo">04 — KALKULATOR ENERGI</span><h2>Kebiasaan kecil juga dapat dihitung.</h2><p>Atur daya lampu dan lama pemakaian untuk memperkirakan konsumsi selama 30 hari.</p></div><div className="calcBox"><label>Daya lampu <b>{watts} watt</b><input type="range" min="5" max="60" value={watts} onChange={e=>setWatts(+e.target.value)}/></label><label>Dipakai per hari <b>{hours} jam</b><input type="range" min="1" max="24" value={hours} onChange={e=>setHours(+e.target.value)}/></label><div className="calcResult"><span>Perkiraan konsumsi</span><strong>{kwh} kWh</strong><small>selama 30 hari</small></div><p>Rumus: daya (watt) × waktu (jam) ÷ 1.000. Mematikan lampu saat tidak dibutuhkan mengurangi konsumsi tanpa mengurangi manfaatnya.</p></div></section>
 <section className="ready"><span>SUDAH SELESAI BELAJAR?</span><h2>Saatnya uji pemahamanmu.</h2><p>Sepuluh soal akan menguji konsep, cara kerja, dan penerapan energi terbarukan.</p><Link className="primary" href="/kuis">Mulai Kuis →</Link></section><Footer/></main>
}
