"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import Nav from "../../components/Nav";
import Footer from "../../components/Footer";
const quiz=[
 {q:"Pernyataan yang paling tepat tentang energi terbarukan adalah…",o:["Tidak menimbulkan dampak apa pun","Pulih melalui proses alam dalam skala waktu manusia","Selalu tersedia dengan jumlah tetap","Tidak memerlukan teknologi"],a:1,x:"Terbarukan berarti sumbernya dapat pulih melalui proses alam. Pemanfaatannya tetap memiliki biaya dan dampak yang perlu dikelola."},
 {q:"Urutan perubahan energi pada PLTB yang benar adalah…",o:["Kimia → panas → listrik","Gerak angin → gerak turbin → listrik","Cahaya → panas → gerak","Panas bumi → cahaya → listrik"],a:1,x:"Energi kinetik angin memutar rotor turbin, kemudian generator mengubah energi mekanik menjadi listrik."},
 {q:"Mengapa panel surya sering dipadukan dengan baterai atau jaringan listrik?",o:["Panel hanya bekerja di malam hari","Produksinya berubah mengikuti sinar matahari","Baterai menghasilkan cahaya matahari","Agar panel menghasilkan angin"],a:1,x:"Produksi surya bersifat berubah-ubah. Penyimpanan atau jaringan membantu menyeimbangkan waktu produksi dan penggunaan."},
 {q:"Sebuah desa memiliki sungai berarus stabil dengan beda tinggi yang cukup. Teknologi yang paling relevan adalah…",o:["Mikrohidro","PLTB","Biogas","PLTS terapung"],a:0,x:"Mikrohidro memanfaatkan debit dan beda tinggi air dalam skala yang sesuai untuk kebutuhan lokal."},
 {q:"Biomassa belum tentu ramah lingkungan apabila…",o:["Menggunakan residu pertanian","Bahan bakunya diambil dengan merusak hutan","Limbah dikelola dengan baik","Biogas menggantikan pembakaran terbuka"],a:1,x:"Keberlanjutan biomassa bergantung pada asal bahan baku dan emisinya. Penggundulan hutan dapat menghilangkan manfaat lingkungannya."},
 {q:"Keunggulan utama panas bumi dibanding surya dan angin adalah…",o:["Bisa dibangun di semua tempat","Tidak membutuhkan biaya awal","Dapat beroperasi relatif stabil siang dan malam","Tidak memiliki dampak lingkungan"],a:2,x:"Panas bumi dapat menyediakan pasokan yang stabil, tetapi hanya layak di wilayah geologi tertentu."},
 {q:"Mengapa energi fosil disebut tidak terbarukan?",o:["Tidak dapat menghasilkan listrik","Proses terbentuknya jauh lebih lambat daripada pemakaiannya","Tidak tersimpan di bumi","Hanya digunakan kendaraan"],a:1,x:"Batu bara, minyak, dan gas memerlukan waktu geologis sangat panjang untuk terbentuk kembali."},
 {q:"Lampu 10 watt menyala 5 jam sehari. Energi yang dipakai per hari adalah…",o:["0,05 kWh","0,5 kWh","2 kWh","50 kWh"],a:0,x:"10 watt × 5 jam = 50 Wh = 0,05 kWh."},
 {q:"Pertimbangan yang paling lengkap saat memilih sumber energi adalah…",o:["Hanya harga alat","Hanya jumlah listrik","Potensi alam, biaya, keandalan, masyarakat, dan lingkungan","Sumber yang paling populer"],a:2,x:"Keputusan energi melibatkan aspek teknis, ekonomi, sosial, dan lingkungan sekaligus."},
 {q:"Tindakan yang langsung mengurangi konsumsi energi tanpa membeli alat baru adalah…",o:["Membiarkan pengisi daya terpasang","Menyalakan pendingin saat ruangan kosong","Mematikan lampu dan proyektor setelah digunakan","Membuka pintu kulkas lama-lama"],a:2,x:"Efisiensi dan penghematan dimulai dari menghindari pemakaian yang tidak memberi manfaat."}
];
export default function Kuis(){const [started,setStarted]=useState(false),[i,setI]=useState(0),[pick,setPick]=useState<number|null>(null),[answers,setAnswers]=useState<number[]>([]);const score=useMemo(()=>answers.filter((v,n)=>v===quiz[n].a).length,[answers]);function next(){if(pick===null)return;setAnswers(v=>[...v,pick]);setPick(null);setI(v=>v+1)}function reset(){setStarted(false);setI(0);setPick(null);setAnswers([])}return <main className="quizPage"><Nav active="kuis"/><section className="quizShell"><div className="quizIntro"><span className="sectionNo light">UJI PEMAHAMAN</span><h1>Tantangan<br/>Energi Kita</h1><p>Jawab berdasarkan konsep, bukan sekadar hafalan. Pembahasan muncul setelah kamu memilih.</p><div className="quizMeta"><span>10 SOAL</span><span>± 7 MENIT</span><span>PEMBAHASAN LANGSUNG</span></div><Link href="/belajar">← Kembali belajar</Link></div><div className="quizBox">{!started?<div className="quizStart"><div className="bolt">⚡</div><h2>Siap memulai?</h2><p>Kamu tidak dibatasi waktu. Pilih satu jawaban terbaik pada setiap soal.</p><button onClick={()=>setStarted(true)}>Mulai Kuis →</button></div>:i<quiz.length?<><div className="progress"><span>SOAL {i+1} DARI {quiz.length}</span><div><i style={{width:`${(i+1)*10}%`}}/></div></div><h2 className="question">{quiz[i].q}</h2><div className="options">{quiz[i].o.map((o,n)=><button key={o} disabled={pick!==null} onClick={()=>setPick(n)} className={pick===null?"":n===quiz[i].a?"correct":n===pick?"wrong":"muted"}><b>{String.fromCharCode(65+n)}</b>{o}<span>{pick!==null&&n===quiz[i].a?"✓":pick===n?"×":""}</span></button>)}</div>{pick!==null&&<div className={`feedback ${pick===quiz[i].a?"yes":"no"}`}><strong>{pick===quiz[i].a?"Tepat!":"Belum tepat."}</strong> {quiz[i].x}</div>}<button className="next" disabled={pick===null} onClick={next}>{i===quiz.length-1?"Lihat hasil":"Soal berikutnya"} →</button></>:<div className="result"><div className="scoreRing"><strong>{score}</strong><span>/10</span></div><h2>{score>=9?"Luar biasa!":score>=7?"Pemahamanmu kuat!":score>=5?"Awal yang baik!":"Yuk, pelajari kembali."}</h2><p>{score>=7?"Kamu telah memahami sebagian besar konsep energi terbarukan.":"Buka kembali materi, khususnya bagian yang masih membingungkan, lalu coba lagi."}</p><div className="resultActions"><button onClick={reset}>Ulangi kuis ↻</button><Link href="/belajar">Pelajari lagi</Link></div></div>}</div></section><Footer/></main>}
